/*
 * Automatically generated by jrpcgen 1.0.7 on 01/12/11 13:22
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
/**
 * A collection of constants used by the "RPCWhiteboard" ONC/RPC program.
 */
public interface RPCWhiteboard {
    public static final int close_1 = 3;
    public static final int WHITEBOARD_PROG = 0x6a3b7ca0;
    public static final int readMessage_1 = 2;
    public static final int sendMessage_1 = 1;
    public static final int WHITEBOARD_VERS = 1;
}
// End of RPCWhiteboard.java
